//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BallotBox
    {
        public int id { get; set; }
        public string numBallot { get; set; }
        public int cityId { get; set; }
        public string MIdentity { get; set; }
    
        public virtual City City { get; set; }
        public virtual Managers Managers { get; set; }
    }
}
