//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class National
    {
        public string Identity { get; set; }
        public string fullName { get; set; }
        public string street { get; set; }
        public string zipCode { get; set; }
        public string numHouse { get; set; }
        public int cityId { get; set; }
        public string numBallot { get; set; }
        public bool IsChoose { get; set; }
    
        public virtual City City { get; set; }
    }
}
