//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factions
    {
        public int Id { get; set; }
        public string factionName { get; set; }
        public int voters { get; set; }
        public string leadersMail { get; set; }
        public string factionPic { get; set; }
        public bool IsAgree { get; set; }
        public string fanctionsStageName { get; set; }
    
        public virtual FinalResults FinalResults { get; set; }
    }
}
