//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalResults
    {
        public int idFaction { get; set; }
        public int idVote { get; set; }
        public int numberOfVote { get; set; }
    
        public virtual Factions Factions { get; set; }
        public virtual Voting Voting { get; set; }
    }
}
